name: SpectatorPlus
main: com.pgcraft.spectatorplus.SpectatorPlus
version: '3.0'
description: "Lets players spectate other competitors in events, games, etc. when they're not playing. Allows them to fly but stops them helping other players. Do [/spec help] for help!"
author: pgmann
authors: ["AmauryPi"]

commands:
  spectate:
    description: 'See /<command> help for help'
    usage: 'See /<command> help for help'
    aliases: spec

permissions:
  spectate.*:
    description: Allows you to spectate and stops players spectating you
    children:
      spectate.use: true
      spectate.admin: true
    default: false
  spectate.use:
    description: Allows you to enable and disable spectate mode for yourself
    default: op
    children:
      spectate.use.on: true
      spectate.use.off: true
  spectate.use.on:
    description: Allows you to enable spectate mode for yourself
    default: op
  spectate.use.off:
    description: Allows you to disable spectate mode for yourself
    default: op
  spectate.use.others:
    description: Allows you to enable and disable spectate mode for others [/spec on <player>]
    default: op
  spectate.admin:
    description: Allows you to manage all setup and admin commands in SpectatorPlus
    default: op
    children:
      spectate.use.others: true
      spectate.admin.lobby: true
      spectate.admin.mode: true
      spectate.admin.arena: true
      spectate.admin.reload: true
      spectate.admin.say: true
      spectate.admin.config: true
      spectate.admin.hide: true
      spectate.admin.hide.see: true
      spectate.admin.bypasswhitelist: true
      spectate.admin.list: true
      spectate.admin.shout: true
  spectate.admin.lobby:
    description: Allows you to set the global lobby
    default: op
  spectate.admin.mode:
    description: Allows you to set the plugin mode
    default: op
  spectate.admin.arena:
    description: Allows you to manage arenas
    default: op
  spectate.admin.reload:
    description: Allows you to reload the plugin
    default: op
  spectate.admin.list:
    description: Allows you to list the spectators
    default: op
  spectate.admin.hide:
    description: Toggle to stop players spectating you (default off)
    default: op
    children:
      spectate.admin.hide.self: true
      spectate.admin.hide.others: true
  spectate.admin.hide.self:
    description: Toggle to stop players spectating you (default off)
    default: op
  spectate.admin.hide.others:
    description: Toggle to stop players spectating the selected player (default off)
    default: op
  spectate.admin.hide.see:
    description: Players with this permission will still be able to see hidden players
    default: op
  spectate.admin.hide.auto:
    description: When you log in, you are hidden from the teleporter by default
    default: false
  spectate.admin.config:
    description: Allows you to edit the plugin configuration ingame
    default: op
    children:
      spectate.admin.reload: true
  spectate.admin.say:
    description: Allows you to send a message only to the spectators
    default: op
  spectate.admin.bypasswhitelist:
    description: |
      Allows a player to bypass the commands whitelist while spectating: he will be able to send any command.
      Only effective if the chat.blockCommands.adminBypass configuration option is set to true.
    default: op
  spectate.admin.shout:
    description: Allows a spectator's chat to be visible to non-spectators
