# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Master

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "docs/*"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "docs/*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: pgmann-public
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build with Maven
      run: mvn --batch-mode package javadoc:javadoc --file SpectatorPlus/pom.xml
    - name: Archive final plugin JAR
      uses: actions/upload-artifact@v2
      with:
        name: SpectatorPlus Plugin
        path: SpectatorPlus/target/SpectatorPlus-*-SNAPSHOT.jar
    - name: Publish JAR to Maven Repo
      if: ${{ github.event_name == 'push' }}
      run: mvn --batch-mode deploy --file SpectatorPlus/pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.MVN_UPLOAD_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MVN_UPLOAD_PASSWORD }}
    - name: Push update to javadocs
      if: ${{ github.event_name == 'push' }}
      run: |
        rm -rf docs/javadoc
        mv SpectatorPlus/target/site/apidocs docs/javadoc
        git config --global user.name "Github Actions"
        git config --global user.email "noreply@github.com"
        git add docs/javadocs
        git commit -m "Update javadocs"
        git push
